-- ==============================================================================
-- FleetIQ Database Schema Migration: V1__initial_schema.sql
-- Compatible with: PostgreSQL 15/16 and H2 (PostgreSQL compatibility mode)
-- ==============================================================================

-- 1. VEHICLES TABLE
CREATE TABLE vehicles (
    id VARCHAR(32) NOT NULL,
    vin VARCHAR(64) NOT NULL,
    registration_number VARCHAR(32),
    make VARCHAR(32) NOT NULL,
    model VARCHAR(64) NOT NULL,
    model_year INTEGER,
    fuel_type VARCHAR(32),
    vehicle_type VARCHAR(32),
    mileage_km BIGINT,
    status VARCHAR(32),
    battery_health_pct DOUBLE PRECISION,
    oil_life_pct DOUBLE PRECISION,
    tire_pressure_psi DOUBLE PRECISION,
    avg_mpg DOUBLE PRECISION,
    last_service_date DATE,
    created_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_vehicles PRIMARY KEY (id),
    CONSTRAINT uq_vehicles_vin UNIQUE (vin)
);

CREATE INDEX idx_vehicles_status ON vehicles(status);
CREATE INDEX idx_vehicles_make_model ON vehicles(make, model);


-- 2. CANONICAL VEHICLE EVENTS TABLE
CREATE TABLE canonical_vehicle_events (
    event_id VARCHAR(64) NOT NULL,
    vehicle_id VARCHAR(32) NOT NULL,
    event_type VARCHAR(64) NOT NULL,
    severity VARCHAR(32),
    fault_code VARCHAR(32),
    idle_minutes INTEGER,
    oil_life_pct DOUBLE PRECISION,
    battery_health_pct DOUBLE PRECISION,
    tire_pressure_psi DOUBLE PRECISION,
    fuel_consumed_liters DOUBLE PRECISION,
    operating_hours DOUBLE PRECISION,
    odometer_km BIGINT,
    source VARCHAR(64) NOT NULL,
    processing_status VARCHAR(32),
    raw_payload TEXT,
    event_timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
    ingested_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_canonical_vehicle_events PRIMARY KEY (event_id)
);

CREATE INDEX idx_cve_vehicle_id ON canonical_vehicle_events(vehicle_id);
CREATE INDEX idx_cve_event_timestamp ON canonical_vehicle_events(event_timestamp);
CREATE INDEX idx_cve_severity ON canonical_vehicle_events(severity);
CREATE INDEX idx_cve_event_type ON canonical_vehicle_events(event_type);


-- 3. FLEET ACTIONS TABLE
CREATE TABLE fleet_actions (
    action_id VARCHAR(64) NOT NULL,
    decision_id VARCHAR(64),
    vehicle_id VARCHAR(32) NOT NULL,
    issue VARCHAR(128) NOT NULL,
    priority VARCHAR(32) NOT NULL,
    severity VARCHAR(32) NOT NULL,
    estimated_impact DOUBLE PRECISION,
    recommended_action VARCHAR(255) NOT NULL,
    confidence DOUBLE PRECISION,
    status VARCHAR(32) NOT NULL,
    decision_source VARCHAR(64),
    requires_human_review BOOLEAN DEFAULT FALSE,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE,
    resolved_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_fleet_actions PRIMARY KEY (action_id)
);

CREATE INDEX idx_actions_vehicle_id ON fleet_actions(vehicle_id);
CREATE INDEX idx_actions_priority ON fleet_actions(priority);
CREATE INDEX idx_actions_status ON fleet_actions(status);
CREATE INDEX idx_actions_created_at ON fleet_actions(created_at);


-- 4. FLEET DECISIONS TABLE
CREATE TABLE fleet_decisions (
    decision_id VARCHAR(64) NOT NULL,
    event_id VARCHAR(64),
    vehicle_id VARCHAR(32) NOT NULL,
    issue_detected VARCHAR(64) NOT NULL,
    decision_type VARCHAR(64),
    recommended_action VARCHAR(255) NOT NULL,
    priority VARCHAR(32) NOT NULL,
    estimated_cost_impact DOUBLE PRECISION,
    confidence_score DOUBLE PRECISION,
    decision_source VARCHAR(64) NOT NULL,
    rationale TEXT,
    requires_human_review BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_fleet_decisions PRIMARY KEY (decision_id)
);

CREATE INDEX idx_decisions_vehicle_id ON fleet_decisions(vehicle_id);
CREATE INDEX idx_decisions_event_id ON fleet_decisions(event_id);
CREATE INDEX idx_decisions_source ON fleet_decisions(decision_source);
CREATE INDEX idx_decisions_priority ON fleet_decisions(priority);


-- 5. RAW INGESTION RECORDS TABLE
CREATE TABLE raw_ingestion_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source VARCHAR(64),
    raw_payload TEXT,
    status VARCHAR(32),
    error_message VARCHAR(512),
    received_at TIMESTAMP WITH TIME ZONE
);

CREATE INDEX idx_raw_ingest_source ON raw_ingestion_records(source);
CREATE INDEX idx_raw_ingest_received ON raw_ingestion_records(received_at);


-- 6. USERS TABLE
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(64) NOT NULL,
    password VARCHAR(128) NOT NULL,
    full_name VARCHAR(128) NOT NULL,
    role VARCHAR(32) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_users_username UNIQUE (username)
);

CREATE INDEX idx_users_username ON users(username);
