-- ==============================================================================
-- FleetIQ Database Schema Migration: V2__user_audit_and_copilot_chat.sql
-- Compatible with: PostgreSQL 15/16 and H2 (PostgreSQL compatibility mode)
-- ==============================================================================

-- 1. USER AUDIT LOGS TABLE
CREATE TABLE user_audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_username VARCHAR(64) NOT NULL,
    action VARCHAR(64) NOT NULL,
    target_username VARCHAR(64) NOT NULL,
    details VARCHAR(512),
    ip_address VARCHAR(64),
    timestamp TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_audit_actor ON user_audit_logs(actor_username);
CREATE INDEX idx_audit_timestamp ON user_audit_logs(timestamp);
CREATE INDEX idx_audit_target ON user_audit_logs(target_username);


-- 2. CHAT CONVERSATIONS TABLE (USER-SPECIFIC PERSISTENT COPILOT THREADS)
CREATE TABLE chat_conversations (
    id VARCHAR(64) NOT NULL,
    user_id VARCHAR(64) NOT NULL,
    title VARCHAR(255) NOT NULL,
    archived BOOLEAN DEFAULT FALSE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_chat_conversations PRIMARY KEY (id)
);

CREATE INDEX idx_conversations_user ON chat_conversations(user_id);
CREATE INDEX idx_conversations_updated ON chat_conversations(updated_at);


-- 3. CHAT MESSAGES TABLE (MULTI-TURN USER MESSAGES & AI RESPONSES)
CREATE TABLE chat_messages (
    id VARCHAR(64) NOT NULL,
    conversation_id VARCHAR(64) NOT NULL,
    role VARCHAR(32) NOT NULL,
    content TEXT NOT NULL,
    query_type VARCHAR(32),
    sources TEXT,
    evidence TEXT,
    confidence DOUBLE PRECISION,
    model_provider VARCHAR(64),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_chat_messages PRIMARY KEY (id),
    CONSTRAINT fk_chat_msg_conv FOREIGN KEY (conversation_id) REFERENCES chat_conversations(id) ON DELETE CASCADE
);

CREATE INDEX idx_chat_msg_conv ON chat_messages(conversation_id);
CREATE INDEX idx_chat_msg_created ON chat_messages(created_at);
