-- ==============================================================================
-- FleetIQ Database Schema Migration: V3__auth_tokens_and_user_lifecycle.sql
-- Compatible with: PostgreSQL 15/16 and H2 (PostgreSQL compatibility mode)
-- ==============================================================================

-- 1. EXTEND USERS TABLE WITH LIFECYCLE, VERIFICATION & SECURITY FIELDS
ALTER TABLE users ADD COLUMN email VARCHAR(128);
ALTER TABLE users ADD COLUMN email_verified BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE users ADD COLUMN last_login_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE users ADD COLUMN failed_attempts INTEGER DEFAULT 0 NOT NULL;
ALTER TABLE users ADD COLUMN locked_until TIMESTAMP WITH TIME ZONE;
ALTER TABLE users ADD COLUMN organization VARCHAR(128);

-- Backfill existing default seed users with corporate email addresses
UPDATE users SET email = 'admin@fleetiq.internal', email_verified = TRUE, organization = 'FleetIQ Core Ops' WHERE username = 'admin';
UPDATE users SET email = 'ops@fleetiq.internal', email_verified = TRUE, organization = 'FleetIQ Core Ops' WHERE username = 'ops_lead';
UPDATE users SET email = 'operator@fleetiq.internal', email_verified = TRUE, organization = 'FleetIQ Dispatch' WHERE username = 'operator';
UPDATE users SET email = 'viewer@fleetiq.internal', email_verified = TRUE, organization = 'FleetIQ Analytics' WHERE username = 'viewer';

-- Ensure email uniqueness
CREATE UNIQUE INDEX idx_users_email ON users(email);


-- 2. REFRESH TOKENS TABLE (STATEFUL SESSION PERSISTENCE & ROTATION)
CREATE TABLE refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash VARCHAR(128) NOT NULL,
    user_id BIGINT NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    revoked BOOLEAN DEFAULT FALSE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    ip_address VARCHAR(64),
    user_agent VARCHAR(256),
    CONSTRAINT uq_refresh_tokens_hash UNIQUE (token_hash),
    CONSTRAINT fk_refresh_token_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_refresh_tokens_hash ON refresh_tokens(token_hash);
CREATE INDEX idx_refresh_tokens_user ON refresh_tokens(user_id);


-- 3. PASSWORD RESET TOKENS TABLE (CRYPTOGRAPHIC SINGLE-USE RESET FLOW)
CREATE TABLE password_reset_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash VARCHAR(128) NOT NULL,
    user_id BIGINT NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    used BOOLEAN DEFAULT FALSE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_password_reset_hash UNIQUE (token_hash),
    CONSTRAINT fk_reset_token_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_reset_token_hash ON password_reset_tokens(token_hash);
CREATE INDEX idx_reset_token_user ON password_reset_tokens(user_id);
